#!/bin/bash

function mysql_hook {
	pid_mysql=$(pidof mysqld)
	sleep ${TPCC_HOOK_SLEEP_TIME} && sudo bpftrace ${LOCAL_DIR}/utils/bpftrace/mysql_uprobe.bt $pid_mysql | tee $1-bpftrace.txt &
}

function mysql_hook_end {
	set +e
	sudo killall bpftrace
	set -e
}

function bench_single_main_mysql_trace {
	source $LOCAL_DIR/bench/mysql/fn_mysql
	bench_single_main_mysql
}
