#!/bin/bash

TPCC_DIR="/home/bbn/tpcc-mysql/"
MYSQL_CONF="/etc/my.cnf"
TPCC_WH=100
TPCC_DB_NAME="tpcc${TPCC_WH}"

function mysql_hook {
	pid_mysql=$(pidof mysqld)
	sudo bpftrace ${BENCH_DIR}/call_path.bt $pid_mysql | tee $1-bpftrace.txt &
}

function mysql_hook_end {
	set +e
	sudo killall bpftrace
	set -e
}

function bench_single_main_mysql_trace {
	bench_single_main_mysql
}
