#!/bin/bash

## Mysql Setting
source ${LOCAL_DIR}/profile/bench/mysql/mysql_norm

TPCC_DIR="/home/chenlf/tpcc-mysql"
MYSQL_CONF="/etc/my.cnf"
MYSQL_BUFFERPOOL="10G"
TPCC_WH=1000
TPCC_DB_NAME="tpcc${TPCC_WH}"
TPCC_RUNTIME=1800
TPCC_WARMUP_TIME=120
TPCC_CLIENT=16

TPCC_HOOK_SLEEP_TIME=$((TPCC_WARMUP_TIME - 10))
