#!/bin/bash

FLAME_GRAPH_DIR=/home/bbn/FlameGraph

function post_process {
    for i in $(find "$1" -type f -name '*-perf.log'); do
        perf script -i $i | $FLAME_GRAPH_DIR/stackcollapse-perf.pl | $FLAME_GRAPH_DIR/flamegraph.pl >$i.svg
    done
}
