#!/bin/bash

function bench_single_main {
    for pattern in $SETTING_FIO_PATTERN; do
        for size in $SETTING_FIO_BSIZE; do
            for thread in $SETTING_FIO_THREAD; do
                zoned_cleanup
                sudo blkzone reset "${CONFIG_ZONED_DEV}"
                zoned_format_"${bench_fs}"
                zoned_mount_"${bench_fs}"
                sleep 2
                sleep 2 && sudo bpftrace ${BPFTRACE_DIR}/time_trace.bt | tee "$1"-"$pattern"-"$size"-t"$thread"-bpftrace-time.log &
                sleep 2 && sudo bpftrace ${BPFTRACE_DIR}/call_path.bt | tee "$1"-"$pattern"-"$size"-t"$thread"-bpftrace-path.log &
                numactl -N 0 -m 0 perf record -g -F 99 -o $1-"$pattern"-"$size"-t"$thread"-perf.log -- fio --name=benchmark \
                    --rw="$pattern" \
                    --numjobs="$thread" \
                    --ioengine=psync \
                    --bs="$size" \
                    --runtime="${SETTING_FIO_RUNTIME}" \
                    --time_based \
                    --group_reporting \
                    --output="$1"-"$pattern"-"$size"-t"$thread".log \
                    --directory="${CONFIG_MOUNTPOINT}" \
                    --size="${SETTING_FIO_SIZE}" \
                    --blockalign=4096 \
                    --mem_align=4096
                set +e
                sudo pkill bpftrace
                set -e
                wait
            done
        done
    done
}
