#!/bin/bash

# Breakdown:
#  +DMA +load_balancing +concurrency_control +remapping_scatter +bulk_read_split +threshold_read
#  -threshold_write

# Not Viable for test
# echo "Not viable for test!"
# exit 1

setting_bench="filebench"
setting_fs="nova"
setting_skt_setup="SS"
setting_method_setup="DMA"
setting_write_thresh="0"
setting_read_thresh="32768"
setting_watermark="10000" # Deprecated
setting_user_nums="4"
setting_chunk="2"
setting_main_wr="0" # Deprecated
setting_worker_wr="1" # Deprecated
setting_scatter="1"
setting_remote_write_thresh="0"
setting_remote_read_thresh="32768"

