#!/bin/bash

# Breakdown: CPU

setting_bench="graphwalker"
setting_fs="nova"
setting_skt_setup="DS SS"
setting_method_setup="DMA"
setting_write_thresh="16384"
setting_read_thresh="65536"
setting_watermark="10000" # Deprecated
setting_user_nums="8"
setting_chunk="2"
setting_main_wr="0" # Deprecated
setting_worker_wr="1" # Deprecated
setting_scatter="0"
setting_remote_write_thresh="16384"
setting_remote_read_thresh="16384"
