#!/bin/bash

S16K=16384
S32K=32768
S64K=65536
S128K=131072
S256K=262144
S512K=524288

set -e
set -x

export GRAPHCHI_ROOT=/home/gloit/GraphWalker-master
GRAPHCHI_DATA_DIR=/data2

function bench_single_main {
  PREFIX=$1
  cp -ra /data2/kron30_32_GraphWalker /mnt/pmem

  for repeat in $(seq 1 1); do
    NAME=$PREFIX-msppr-$repeat
    ${BENCH_DIR}/graph_iter.bt >$NAME-stat &
    BPF_PID=$!
    $numactl_cmd $GRAPHCHI_ROOT/bin/apps/msppr \
      file $GRAPHCHI_DATA_DIR/kron30_32_sorted.txt \
      csrfiles $MOUNT_DIR/kron30_32 \
      firstsource 0 \
      numsources 20 \
      walkspersource 2000 \
      maxwalklength 20 \
      prob 0.2 >$NAME &
    cat /proc/`pidof msppr`/stat > $NAME-msppr-$repeat-proc-before
    WORK_PID=$!
    while ps -p $WORK_PID >/dev/null; do
      sleep 1
    done
    cat /proc/`pidof msppr`/stat > $NAME-msppr-$repeat-proc-after
    kill $BPF_PID

    NAME=$PREFIX-graphlet-$repeat
    $BENCH_DIR/graph_iter.bt >$NAME-stat &
    BPF_PID=$!
    ${numactl_cmd} $GRAPHCHI_ROOT/bin/apps/graphlet \
      file $GRAPHCHI_DATA_DIR/kron30_32_sorted.txt \
      csrfiles $MOUNT_DIR/kron30_32 \
      N 1073741824 \
      R 10000 \
      L 4 \
      prob 0.2 >$NAME &
    cat /proc/`pidof msppr`/stat > $NAME-graphlet-$repeat-proc-before
    WORK_PID=$!
    while ps -p $WORK_PID >/dev/null; do
      sleep 1
    done
    cat /proc/`pidof msppr`/stat > $NAME-graphlet-$repeat-proc-after
    kill $BPF_PID

    NAME=$PREFIX-simrank-$repeat
    $BENCH_DIR/graph_iter.bt >$NAME-stat &
    BPF_PID=$!
    $numactl_cmd $GRAPHCHI_ROOT/bin/apps/simrank \
      file $GRAPHCHI_DATA_DIR/kron30_32_sorted.txt \
      csrfiles $MOUNT_DIR/kron30_32 \
      a 1 \
      b 2 \
      R 1400 \
      L 11 \
      prob 0.2 >$NAME &
    cat /proc/`pidof msppr`/stat > $NAME-simrank-$repeat-proc-before
    WORK_PID=$!
    while ps -p $WORK_PID >/dev/null; do
      sleep 1
    done
    cat /proc/`pidof msppr`/stat > $NAME-simrank-$repeat-proc-after
    kill $BPF_PID
  done
}

