#!/bin/bash

# All functions require argument:
#  $1 for dev

function normal_mount_generic {
	sudo mount -t "$2" "$1" "${CONFIG_MOUNTPOINT}"
}

function normal_format_ext4 {
	sudo mkfs.ext4 -F "$1"
}

function normal_mount_ext4 {
	mount_generic "$1" "ext4"
}

function normal_format_xfs {
	sudo mkfs.xfs -f -m "$1"
}

function normal_mount_xfs {
	mount_generic "$1" "xfs"
}

function normal_format_f2fs {
	sudo mkfs.f2fs -f -m "$1"
}

function normal_mount_f2fs {
	mount_generic "$1" "f2fs"
}
