#!/bin/bash

function setup_loop {
    sudo losetup -D
    set +e
    sudo umount ./tmp
    set -e
    if [[ ${CONFIG_USE_LOOP_AS_CONV} == "1" ]]; then
        if [[ ${CONFIG_LOOP_IN_RAM} == "1" ]]; then
            mkdir -p tmp
            sudo mount -t tmpfs none tmp
            loop_filename="tmp/loop.img"
        else
            loop_filename="./loop.img"
        fi
        sudo dd if=/dev/zero of="${loop_filename}" bs=1M count="$((CONFIG_LOOP_SIZE * 1024))"
        sudo losetup -D
        export CONFIG_CONV_DEV=$(sudo losetup -b 4096 --find --show "${loop_filename}")
    fi
}
