#!/bin/bash

function setup_loop {
	sudo losetup -D
	set +e
	sudo umount ./tmp > /dev/null 2>&1
	set -e
	if [[ ${CONFIG_USE_LOOP_AS_CONV} == "1" ]]; then
		if [[ ${CONFIG_LOOP_IN_RAM} == "1" ]]; then
			mkdir -p tmp
			sudo mount -t tmpfs none tmp
			loop_filename="tmp/loop.img"
		else
		size=$((CONFIG_LOOP_SIZE * 1024 * 1024 * 1024))
		# if the file exist and the size matches, skip
		if [[ -f "${loop_filename}" ]]; then
			filesize=$(stat -c%s "${loop_filename}")
			if [[ $filesize -ne $size ]]; then
				sudo dd if=/dev/zero of="${loop_filename}" bs=1M count="$((CONFIG_LOOP_SIZE * 1024))"
			fi
		fi
		sudo losetup -D
		export CONFIG_CONV_DEV=$(sudo losetup --find --show "${loop_filename}")
	fi
}

function inline_func {
	while read line; do
		if [[ $line =~ (\.|source).+ ]]; then
			file="$(echo $line | cut -d' ' -f2 | envsubst)"
			echo "$(cat "$file")"
		else
			echo "$line"
		fi
	done <"$1"
}

function gen_perfflame {
	if [[ -z $FLAME_GRAPH_DIR ]]; then
		FLAME_GRAPH_DIR=/home/bbn/FlameGraph
		warn "FLAME_GRAPH_DIR is not set, using default: $FLAME_GRAPH_DIR"
	fi

	info "Generating perf gragh for $1"
	basename_file=$(basename "$1")
	out_filename=${basename_file}.svg
	perf script -i "$1" | $FLAME_GRAPH_DIR/stackcollapse-perf.pl | $FLAME_GRAPH_DIR/flamegraph.pl >"$2"/$out_filename || true
}

export ROOT_DIR_BENCH=`pwd`

function croot {
	cd $ROOT_DIR_BENCH
}

# info: print in green
function info {
	echo -e "\e[32m$1\e[0m"
}

# warn: print in yellow
function warn {
	echo -e "\e[33m$1\e[0m"
}

# error: print in red
function error {
	echo -e "\e[31m$1\e[0m"
}
