#!/bin/bash

function start_perf {
	pid=$(pidof mysqld)
	sleep ${TPCC_HOOK_SLEEP_TIME} && info "Starting perf 1" && perf record -F 10 -o $1-mysql.perf -p $pid -- sleep ${TPCC_RUNTIME} &
	sleep ${TPCC_HOOK_SLEEP_TIME} && info "Starting perf 2" && perf record -g -F 99 -o $1-mysql.g.perf -p $pid -- sleep ${TPCC_RUNTIME} &
	sleep ${TPCC_HOOK_SLEEP_TIME} && info "Starting perf 3" && perf stat -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations -p $pid -- sleep ${TPCC_RUNTIME} 2>&1 | tee $1-perf-stats.txt &
}

function start_bpftrace {
	pid=$(pidof mysqld)
	sleep ${TPCC_HOOK_SLEEP_TIME} && info "Starting bpftrace 1" && sudo bpftrace ${LOCAL_DIR}/utils/bpftrace/mysql_uprobe.bt | tee $1-bpftrace.txt &
}

function stop_perf {
	sudo killall perf || true
}

function stop_bpftrace {
	sudo killall bpftrace || true
}

function bench_single_main_mysql {
	cat >${MYSQL_CONF} <<-END
		#
		# This group are read by MySQL server.
		# Use it for options that only the server (but not clients) should see
		#
		# For advice on how to change settings please see
		# http://dev.mysql.com/doc/refman/en/server-configuration-defaults.html
		#
		# Settings user and group are ignored when systemd is used.
		# If you need to run mysqld under a different user or group,
		# customize your systemd unit file for mysqld according to the
		# instructions in http://fedoraproject.org/wiki/Systemd
		[mysqld]
		datadir=/mnt/zns/mysql

		default_storage_engine=InnoDB
		innodb_io_capacity=1000000
		innodb_page_cleaners=4
		innodb_buffer_pool_size=${MYSQL_BUFFERPOOL}
		# innodb_page_size=65536
		# innodb_flush_method=O_DIRECT
		# innodb_flush_sync=1
		# innodb_adaptive_flushing=1
		# innodb_flush_neighbors=0
		# innodb_max_dirty_pages_pct=90
		# innodb_max_dirty_pages_pct_lwm=10
		lower_case_table_names=1
		# large_pages=ON

		# [mysqld_safe]
		# malloc-lib=/usr/lib64/libjemalloc.so
	END

	sync
	sleep 2

	# Initialize MySQL
	sudo mysqld --initialize-insecure > /dev/null 2>&1

	# Chown
	sudo chown -R mysql:mysql ${CONFIG_MOUNTPOINT}/mysql

	# Start MySQL
	systemctl restart mysql

	# Import MySQL DB
	info "==> Importing MySQL DB: ${TPCC_DB_NAME}.sql"
	mysqladmin -u root create ${TPCC_DB_NAME}
	mysql -u root ${TPCC_DB_NAME} <${LOCAL_DIR}/db/${TPCC_DB_NAME}.sql

	# Sleep for some seconds
	sleep 5

	info "==> Pre-bench hook"
	# if this function exist
	mysql_hook $1 || true

	info "==> Running MySQL"
	$numactl_cmd ${TPCC_DIR}/tpcc_start -h 127.0.0.1 -P 3306 -d ${TPCC_DB_NAME} -u root -p "" -w ${TPCC_WH} -c ${TPCC_CLIENT} -r ${TPCC_WARMUP_TIME} -l ${TPCC_RUNTIME} -i 10 | tee $1

	info "==> Post-bench hook"
	mysql_hook_end || true

	# Stop MySQL
	sudo service mysql stop

	unset mysql_hook
	unset mysql_hook_end
}
